### ISSUE TITLE
minor-bug-and-feature-tracker

### ISSUE THREAD

**Issue by iamrishupatel** [iamrishupatel/trello-clone#9]
- [ ] optimise the image on the boards page
- [ ] add roles field 
- [ ] check active sessions on initial load
- [x] make the add another card  button fixed to bottom
- [x] handle user already exists error on create account
- [x] notify user after updates are successful or failed for profile
- [x] update the logo on forms
- [x] add Favicon
- [x] add board name on the board page
- [x] clickaway listener on the label dropdown
- [x] fix comment `<p/>` styles
- [ ] Fix responsiveness
- [ ] remove upload and cancel button after upload is done
- [ ] scroll to task when a new task is created.
- [x] highlight columns while moving tasks
- [ ] better error message for unsupported file uploads
- [ ] Edit board name
- [x] Wrap the text in edit profile page 
      ![image](https://github.com/iamrishupatel/trello-clone/assets/58680469/445ec413-9f91-4a89-9982-b7e8853f9b5c)
- [ ] Fix word wrap issue 
![image](https://github.com/iamrishupatel/trello-clone/assets/58680469/d4189fca-8b9a-4eda-85ab-61c70ec6e58a)
